name: camerax_android
description: "Android implementation of the camerax plugin."
version: 1.2.1
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  camerax_platform_interface: ^1.2.1
  jni: ^0.15.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.0.2
  jnigen: ^0.15.0

flutter:
  plugin:
    implements: camerax
    platforms:
      android:
        package: dev.zeekr.camerax_android
        pluginClass: CameraXAndroidPlugin
        dartPluginClass: CameraXAndroidPlugin
