name: camerax
description: "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."
version: 1.2.1
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  camerax_platform_interface: ^1.2.1
  camerax_android: ^1.2.1
  camerax_ios: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: camerax_android
      ios:
        default_package: camerax_ios
