name: camerax_platform_interface
description: "A common platform interface for the camerax plugin."
version: 1.0.2
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
